
name: dev

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    runs-on: ubuntu-latest
    name: Run Lint & Tests
    steps:
    - uses: actions/checkout@v2
      name: Check out repository

    - uses: actions/setup-node@v1
      name: Set up Node.js
      with:
        node-version: 10.23.2

    - uses: borales/actions-yarn@v2.0.0
      name: Run yarn install
      with:
        cmd: install # will run `yarn install` command

    - name: Run ESLint
      run:
        npm run lint 

    - name: Run tests
      run:
        npm test