# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout:
    runs-on: ubuntu-latest
    name: checkout repository
    steps:
    - uses: actions/checkout@v2
    - name: Check out repository

  install:
    needs: checkout
    runs-on: ubuntu-latest
    name: set up Node.js
    steps:
    - uses: actions/setup-node@v1
    - name: Set up Node.js
      with:
        node-version: 10.23.2
    - uses: borales/actions-yarn@v2.0.0
    - name: Run yarn install
      with:
        cmd: install # will run `yarn install` command
   
  lint: 
    needs: install
    runs-on: ubuntu-latest
    name: Run ESLint
    steps:
    - name: Run ESLint
      run:
        npm run lint     
  test:
  
    # This job contains test called "test"
    needs: lint
    runs-on: ubuntu-latest
    name: test
    steps:
    - name: Run tests
      run:
        npm test